quarkus:
  swagger-ui:
    theme: material
    always-include: true

  live-reload:
    instrumentation: true

  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://postgres-db:5432/bank_accounts
  hibernate-orm:
    database:
      generation: 
       ~: drop-and-create
  oidc:
    auth-server-url: http://localhost:10520/auth/realms/Quarkus
    client-id: customer-app
    credentials:
      secret: 5ffb3490-4d7b-42ed-8cac-e6774550bc92

  container-image:
    build: true
    group: microservices-impacta
    name: account
# Fault Tolerance Test
  isTestingFault: false
# Retry
  isRetry: false
# Timeout
  isFallBack: false

br:
  com:
    impacta:
      microservices:
        ib:
          interfaces:  
            BalanceRestClient/mp-rest/url: http://localhost:9000
            BalanceRestClient/mp-rest/scope: javax.inject.Singleton
            InvestmentsRestClient/mp-rest/url: http://localhost:8500
            InvestmentsRestClient/mp-rest/scope: javax.inject.Singleton
            CreditCardRestClient/mp-rest/url: http://localhost:8200
            CreditCardRestClient/mp-rest/scope: javax.inject.Singleton

# variables
app:
  token-url: http://localhost:10520/auth/realms/quarkus/protocol/openid-connect/token