quarkus:
  swagger-ui:
    always-include: true

  datasource:
    db-kind: postgresql

  live-reload:
    instrumentation: true

# dev profile
"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      username: postgres
      password: postgres
      jdbc:
        url: jdbc:postgresql://localhost:5432/bank_accounts
    hibernate-orm:
      database:
        generation: drop-and-create
    oidc:
      auth-server-url: http://localhost:10520/auth/realms/Quarkus
      client-id: customer-app
      credentials:
        secret: 5ffb3490-4d7b-42ed-8cac-e6774550bc92
                     
# Fault Tolerance Test
  isTestingFault: false
# Retry
  isRetry: false
# Timeout
  isFallBack: false

br:
  com:
    impacta:
      microservices:
        ib:
          interfaces:  
            BalanceRestClient/mp-rest/url: http://localhost:9000/balance
            BalanceRestClient/mp-rest/scope: javax.inject.Singleton
          Debt/mp-rest/url: http://localhost:9010/debt
          Debt/mp-rest/scope: javax.inject.Singleton
          Credit/mp-rest/url: http://localhost:9020/credit
          Credit/mp-rest/scope: javax.inject.Singleton
          Investments/mp-rest/url: http://localhost:8500/investments
          Investments/mp-rest/scope: javax.inject.Singleton
          CreditCard/mp-rest/url: http://localhost:8200/credit-card
          CreditCard/mp-rest/scope: javax.inject.Singleton

# variables
app:
  token-url: http://localhost:10520/auth/realms/quarkus/protocol/openid-connect/token