apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-impacta-debit-ingress
  namespace: microservices-impacta
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: microservices-impacta-debit.com
    http:
      paths:
      - backend:
          service:
            name: ms-impacta-debit-svc
            port: 
              number: 10030
        pathType: Prefix
        path: "/"
  - host: microservices-impacta-credit.com
    http:
      paths:
      - backend:
          service:
            name: ms-impacta-credit-svc
            port: 
              number: 10020
        pathType: Prefix
        path: "/"
  - host: microservices-impacta-extract-balance.com
    http:
      paths:
      - backend:
          service:
            name: ms-impacta-extract-balance-svc
            port: 
              number: 9000
        pathType: Prefix
        path: "/"
  - host: microservices-impacta-credit-card.com
    http:
      paths:
      - backend:
          service:
            name: ms-impacta-credit-card-svc
            port: 
              number: 9010
        pathType: Prefix
        path: "/"
  - host: microservices-impacta-investments.com
    http:
      paths:
      - backend:
          service:
            name: ms-impacta-investments-svc
            port: 
              number: 9020
        pathType: Prefix
        path: "/"
   
  - host: microservices-impacta-keycloak.com
    http:
      paths:
      - backend:
          service:
            name: ms-impacta-keycloak-svc
            port: 
              number: 8080
        pathType: Prefix
        path: "/"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-impacta-account-ingress
  namespace: microservices-impacta
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: microservices-impacta-account.com
    http:
      paths:
      - backend:
          service:
            name: ms-impacta-account-svc
            port: 
              number: 8080
          
        pathType: Prefix
        path: "/"
  