# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-lb
  namespace: microservices-impacta
spec:
  selector:
    app: postgres-db
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432